[package]
name = "hello_axum_seaorm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "api", "migration", "entity"]

[dependencies]
api = { path = "api" }
jsonwebtoken = "8.2.0"
