[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = { version = "^0" }
serde = { version = "1", features = ["derive"] }
chrono = "0.4.23"